/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FooterRoot {}
  interface HeaderRoot {}
  interface MainRoot {}
  interface StencilApp {}
}

declare global {


  interface HTMLFooterRootElement extends Components.FooterRoot, HTMLStencilElement {}
  var HTMLFooterRootElement: {
    prototype: HTMLFooterRootElement;
    new (): HTMLFooterRootElement;
  };

  interface HTMLHeaderRootElement extends Components.HeaderRoot, HTMLStencilElement {}
  var HTMLHeaderRootElement: {
    prototype: HTMLHeaderRootElement;
    new (): HTMLHeaderRootElement;
  };

  interface HTMLMainRootElement extends Components.MainRoot, HTMLStencilElement {}
  var HTMLMainRootElement: {
    prototype: HTMLMainRootElement;
    new (): HTMLMainRootElement;
  };

  interface HTMLStencilAppElement extends Components.StencilApp, HTMLStencilElement {}
  var HTMLStencilAppElement: {
    prototype: HTMLStencilAppElement;
    new (): HTMLStencilAppElement;
  };
  interface HTMLElementTagNameMap {
    'footer-root': HTMLFooterRootElement;
    'header-root': HTMLHeaderRootElement;
    'main-root': HTMLMainRootElement;
    'stencil-app': HTMLStencilAppElement;
  }
}

declare namespace LocalJSX {
  interface FooterRoot {}
  interface HeaderRoot {}
  interface MainRoot {}
  interface StencilApp {}

  interface IntrinsicElements {
    'footer-root': FooterRoot;
    'header-root': HeaderRoot;
    'main-root': MainRoot;
    'stencil-app': StencilApp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'footer-root': LocalJSX.FooterRoot & JSXBase.HTMLAttributes<HTMLFooterRootElement>;
      'header-root': LocalJSX.HeaderRoot & JSXBase.HTMLAttributes<HTMLHeaderRootElement>;
      'main-root': LocalJSX.MainRoot & JSXBase.HTMLAttributes<HTMLMainRootElement>;
      'stencil-app': LocalJSX.StencilApp & JSXBase.HTMLAttributes<HTMLStencilAppElement>;
    }
  }
}


